### ISSUE TITLE
Cuda blocks in Bitcrack

### ISSUE THREAD

**Issue by Dalmatino** [Mizogg/TeamHunter#1]
Hi what means cuda blocks in the Block size part ??

**Comment by Mizogg** [comment]
Hi Dalmatino,

https://github.com/brichard19/BitCrack

-b, --blocks BLOCKS
    The number of CUDA blocks

There are 3 parameters that affect performance: blocks, threads per block, and keys per thread.

blocks: Should be a multiple of the number of compute units on the device. The default is 32.

threads: The number of threads in a block. This must be a multiple of 32. The default is 256.

Keys per thread: The number of keys each thread will process. The performance (keys per second) increases asymptotically with this value. The default is 256. Increasing this value will cause the kernel to run longer, but more keys will be processed.

I have the same information as you

**Comment by ghost3666** [comment]
with this tool is there anyone able to crack??? any success stories, anyone contacted you or shared results, just curious, so what do you recommend about system to run this script or all script included in this GUI..... VGAs or CPU

**Comment by ghost3666** [comment]
is there any file for if the match found or success, or we have to create by ourself like Winner.txt or Win.txt

**Comment by Mizogg** [comment]
Yes any match in your database (btc.txt file) This will save to the found folder. All programs have been tested with Low puzzle 1-64 and all can be found with ease and save correctly
