### ISSUE TITLE
please help with this issue

### ISSUE THREAD

**Issue by maxxxxing** [Mizogg/TeamHunter#15]
![Screenshot 2024-04-26 161436](https://github.com/Mizogg/TeamHunter/assets/162225290/d2a02914-8fca-42df-9bb5-61c3e8d06480)
i am also using visual code 2022 could that be the reason? and python 3.12.3

**Comment by Mizogg** [comment]
Hi Maxxxing,

Sorry you getting the error. I think it is due to your python version you are running 3.12.3. I would uninstall this and install python 3.11


I hope this helps.

Mizogg
