### ISSUE TITLE
AttributeError: module 'qdarktheme' has no attribute 'setup_theme'

### ISSUE THREAD

**Issue by ghost3666** [Mizogg/TeamHunter#2]
TeamHunter.py
pygame 2.5.2 (SDL 2.28.3, Python 3.12.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\Users\Downloads\Compressed\TeamHunter-main\TeamHunter.py", line 415, in <module>
    window = MainWindow()
             ^^^^^^^^^^^^
  File "C:\Users\Downloads\Compressed\TeamHunter-main\TeamHunter.py", line 63, in __init__
    self.load_dark_mode() if self.dark_mode else self.load_light_mode()
                                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Downloads\Compressed\TeamHunter-main\TeamHunter.py", line 70, in load_light_mode
    qdarktheme.setup_theme("light")
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'qdarktheme' has no attribute 'setup_theme'

**Comment by Mizogg** [comment]
Hi Thanks for your question. I think it might be python 3.12 I have not yet tried it with this version of python. I am still running 3.11.

I hope this helps

**Comment by ghost3666** [comment]
i solved with 
import qdarkstyle  # Import qdarkstyle for styling

and i was successfully able to run the script... bro i tried many time but i m unable to join the telegram, also is there any detail video how to use the tool and what settings we should do or not,,,, any document please....

**Comment by Mizogg** [comment]
Send me DM in Telegram I will try and see why you cannot join the group.

This has been created for fun. I have no problems running on Windows 11/10 with Python 3.11.
