### ISSUE TITLE
h160.blf file not found

### ISSUE THREAD

**Issue by ghost3666** [Mizogg/TeamHunter#3]
![image](https://github.com/Mizogg/TeamHunter/assets/93757049/36228897-6478-4804-93f5-f2e0a3cedbc9)

**Comment by Mizogg** [comment]
Please make sure that the h160.blf file is within the input folder.
![image](https://github.com/Mizogg/TeamHunter/assets/88630056/12ac6dc5-3c76-45a8-827d-69c1e28cd417)

Please let me know if this resolves your problem.

**Comment by ghost3666** [comment]
![blf3](https://github.com/Mizogg/TeamHunter/assets/93757049/1653d8df-b4a8-46e8-9af1-5b8ec7eccf53)

**Comment by Mizogg** [comment]
The Bloomfilter you downloaded you got from Icelands Tab and you can also get from Miz Mnemonic tab. This bloomfilter can only be use with these 2 tabs.
Bickcrack keyhunt vanbitcracken All use txt file database.
C# Mnmenonic Uses .blf file another type of Bloom filter but you would have to join there group or read the GitHub from them to understand how to run

**Comment by ghost3666** [comment]
what is new update in version 1?? and also why c#mnemonic reoved

**Comment by Mizogg** [comment]
c#mnemonic Requires additional files these are complicated  to make for most users. I got many question on how to run . I don't use this myself much so just to many unknowns. I have already go a Mnemonic Tab (Miz  Mnemonic ) which offer the same speed and functions better.

Removed Vanbitcracken as could not get it to report to GUI. Also having to many option hard for one person to maintain
