### ISSUE TITLE
address start with "1" Bitcrack only take address starting with 1

### ISSUE THREAD

**Issue by ghost3666** [Mizogg/TeamHunter#5]
"C:\Users\Downloads\Compressed\TeamHunter-main\funct\bitcrack\cuBitcrack" "-d" "0" "-b" "32" "-p" "256" "-t" "256" "--stride" "1" "--keyspace" "20000000000000000:3ffffffffffffffff" "-o" "found\found.txt" "-c" "-i" "input\btc.txt" "--continue" "input\progress.txt" [2023-11-21.20:45:17] [Info] Loading ' input\progress.txt' [2023-11-21.20:45:17] [Info] Compression: compressed [2023-11-21.20:45:17] [Info] Starting at: 0000000000000000000000000000000000000000000000020000D0522F800000 [2023-11-21.20:45:17] [Info] Ending at:   000000000000000000000000000000000000000000000003FFFFFFFFFFFFFFFF [2023-11-21.20:45:17] [Info] Counting by: 0000000000000000000000000000000000000000000000000000000000000001 [2023-11-21.20:45:17] [Info] Initializing NVIDIA GeForce GTX 960M [2023-11-21.20:45:17] [Info] Generating 2,097,152 starting points (80.0MB) [2023-11-21.20:45:18] [Info] 10.0% [2023-11-21.20:45:19] [Info] 20.0% [2023-11-21.20:45:19] [Info] 30.0% [2023-11-21.20:45:19] [Info] 40.0% [2023-11-21.20:45:19] [Info] 50.0% [2023-11-21.20:45:19] [Info] 60.0% [2023-11-21.20:45:20] [Info] 70.0% [2023-11-21.20:45:20] [Info] 80.0% [2023-11-21.20:45:20] [Info] 90.0% [2023-11-21.20:45:20] [Info] 100.0% [2023-11-21.20:45:20] [Info] Done [2023-11-21.20:45:20] [Info] Loading addresses from 'input\btc.txt' [2023-11-21.20:45:20] [Error] Invalid address '3(btc address with 3)' [2023-11-21.20:45:20] [Info] Error: Command execution failed

 "C:\Users\Downloads\Compressed\TeamHunter-main\funct\bitcrack\cuBitcrack" "-d" "0" "-b" "32" "-p" "256" "-t" "256" "--stride" "1" "--keyspace" "800000000000000000000000:ffffffffffffffffffffffff" "-o" "found\found.txt" "-c" "-i" "input\btc.txt" "--continue" "input\progress.txt" [2023-11-21.20:45:49] [Info] Loading ' input\progress.txt' [2023-11-21.20:45:49] [Info] Compression: compressed [2023-11-21.20:45:49] [Info] Starting at: 0000000000000000000000000000000000000000000000020000D0522F800000 [2023-11-21.20:45:49] [Info] Ending at:   000000000000000000000000000000000000000000000003FFFFFFFFFFFFFFFF [2023-11-21.20:45:49] [Info] Counting by: 0000000000000000000000000000000000000000000000000000000000000001 [2023-11-21.20:45:49] [Info] Initializing NVIDIA GeForce GTX 960M [2023-11-21.20:45:49] [Info] Generating 2,097,152 starting points (80.0MB) [2023-11-21.20:45:50] [Info] 10.0% [2023-11-21.20:45:50] [Info] 20.0% [2023-11-21.20:45:51] [Info] 30.0% [2023-11-21.20:45:51] [Info] 40.0% [2023-11-21.20:45:51] [Info] 50.0% [2023-11-21.20:45:51] [Info] 60.0% [2023-11-21.20:45:51] [Info] 70.0% [2023-11-21.20:45:52] [Info] 80.0% [2023-11-21.20:45:52] [Info] 90.0% [2023-11-21.20:45:52] [Info] 100.0% [2023-11-21.20:45:52] [Info] Done [2023-11-21.20:45:52] [Info] Loading addresses from 'input\btc.txt' [2023-11-21.20:45:52] [Error] Invalid address '3(btc address with 3)' [2023-11-21.20:45:52] [Info] Error: Command execution failed

**Comment by Mizogg** [comment]
Yes your correct you can read the main GitHub here.  Don't include Address with 3 or bc1

https://github.com/brichard19/BitCrack
