### ISSUE TITLE
Mzogg

### ISSUE THREAD

**Issue by BusyGlimpsy** [Mizogg/TeamHunter#6]

**Comment by ghost3666** [comment]
i have been watching with TeamViewer and old tool tkinter, mostly keys were recovered on 16 January 2015 and i don't know who was the guy that recovered mostly and he withdrawal the money... mostly keys are being found by this tool already recovered a long time ago so what is the purpose of this tool now... after 9 year....

**Comment by ghost3666** [comment]
the comment just you posted in telegram its me, but i m unable to send messages to the group kindly add me or allow me to chat there please....https://t.me/mbilal987 its my id please....

**Comment by ghost3666** [comment]
NVIDIA GeForce G 1243 / 4095MB | 14095 targets 52.57 MKey/s (229,176,916,967,424 total) [03:04:47][2023-11-26.23:06:34] [Info] Checkpoint  
NVIDIA GeForce G 1243 / 4095MB | 14095 targets 52.12 MKey/s (229,180,071,084,032 total) [03:05:47][2023-11-26.23:07:35] [Info] Checkpoint
NVIDIA GeForce G 1243 / 4095MB | 14095 targets 52.57 MKey/s (229,180,169,650,176 total) 
[03:05:49] NVIDIA GeForce G 1243 / 4095MB | 14095 targets 52.12 MKey/s (229,180,268,216,320 total) 

i just wanna know what is the meaning of this ??? is there any key found by this tool or what????  bcz i have not found any key in Found folder or anywhere so what is this Info Checkpoint 

and how many keys are being generated or checked per/second bcz here look like 52.12Mkey/s (million) as per my understandings


i know you are busy too much in your own work, but as i said i was unable to reply in telegram the reason i dont know so i just texted here please.....

**Comment by Mizogg** [comment]
Please message Directly if you cannot get me on here faster replies on Telegram

https://t.me/Mizogg
